from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field, SecretStr

from software_developer_agent.api.routes.jobs import _project_root_for_job
from software_developer_agent.config.settings import get_settings
from software_developer_agent.guardrails.release_policy import publication_allowed
from software_developer_agent.integrations.providers import (
    GitHubProvider,
    SupabaseProvider,
)
from software_developer_agent.integrations.providers.base import ProviderError
from software_developer_agent.orchestration.redis_queue import get_job_queue
from software_developer_agent.persistence.job_store import get_job_store

router = APIRouter(prefix="/providers", tags=["providers"])


class GitHubSyncRequest(BaseModel):
    owner: str = Field(min_length=1, max_length=100)
    repository: str = Field(min_length=1, max_length=100)
    branch: str = Field(default="agentic-forge", min_length=1, max_length=200)
    base_branch: str | None = Field(default=None, max_length=200)
    commit_message: str = Field(
        default="Build generated by Agentic Forge",
        min_length=1,
        max_length=500,
    )
    create_pull_request: bool = True
    pull_request_title: str = Field(
        default="Agentic Forge generated build",
        min_length=1,
        max_length=256,
    )


class SupabaseProjectRequest(BaseModel):
    name: str = Field(min_length=1, max_length=100)
    organization_slug: str = Field(min_length=1, max_length=100)
    database_password: SecretStr
    confirm_billing: bool = False


class SupabaseSecretsRequest(BaseModel):
    secrets: dict[str, SecretStr] = Field(min_length=1, max_length=50)
    confirm_write: bool = False


@router.get("")
def provider_status() -> list[dict[str, Any]]:
    settings = get_settings()
    return [
        GitHubProvider(settings).status().to_dict(),
        SupabaseProvider(settings).status().to_dict(),
    ]


@router.post("/jobs/{job_id}/github/sync")
def sync_job_to_github(job_id: str, payload: GitHubSyncRequest) -> dict[str, Any]:
    job = get_job_store().get(job_id) or get_job_queue().get(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail="Job not found.")
    if not publication_allowed(job):
        raise HTTPException(
            status_code=409,
            detail=(
                "GitHub publication is locked until the build reaches verified status. "
                "The current project remains previewable and downloadable."
            ),
        )
    root = _project_root_for_job(job_id)
    try:
        return GitHubProvider(get_settings()).sync(
            root,
            owner=payload.owner,
            repository=payload.repository,
            branch=payload.branch,
            base_branch=payload.base_branch,
            message=payload.commit_message,
            pull_request_title=(
                payload.pull_request_title if payload.create_pull_request else None
            ),
        )
    except ProviderError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc


@router.post("/supabase/projects", status_code=201)
def create_supabase_project(payload: SupabaseProjectRequest) -> dict[str, Any]:
    try:
        return SupabaseProvider(get_settings()).create_project(
            name=payload.name,
            organization_slug=payload.organization_slug,
            database_password=payload.database_password.get_secret_value(),
            confirm_billing=payload.confirm_billing,
        )
    except ProviderError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc


@router.get("/supabase/projects/{project_ref}/api-keys")
def list_supabase_api_keys(project_ref: str) -> list[dict[str, Any]]:
    try:
        return SupabaseProvider(get_settings()).list_api_keys(project_ref)
    except ProviderError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc


@router.get("/supabase/projects/{project_ref}/storage/buckets")
def list_supabase_storage_buckets(project_ref: str) -> list[dict[str, Any]]:
    try:
        return SupabaseProvider(get_settings()).list_buckets(project_ref)
    except ProviderError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc


@router.get("/supabase/projects/{project_ref}/secrets")
def list_supabase_secrets(project_ref: str) -> list[dict[str, Any]]:
    try:
        return SupabaseProvider(get_settings()).list_secrets(project_ref)
    except ProviderError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc


@router.post("/supabase/projects/{project_ref}/secrets", status_code=201)
def create_supabase_secrets(
    project_ref: str,
    payload: SupabaseSecretsRequest,
) -> dict[str, Any]:
    try:
        return SupabaseProvider(get_settings()).create_secrets(
            project_ref,
            {name: value.get_secret_value() for name, value in payload.secrets.items()},
            confirm_write=payload.confirm_write,
        )
    except ProviderError as exc:
        raise HTTPException(status_code=exc.status_code, detail=str(exc)) from exc
